
Step 1. [Download history price and clean data](/notebooks/forex/hawkeye/1_download.ipynb)

Step 2. [Use monte carlo simulate each stock's movement for 10000 times](/notebooks/forex/hawkeye/2_process.ipynb)

**Step 3. Apply some heuristic rules to give stock recommendation**

In [72]:
import pandas as pd
import matplotlib.pyplot as plt

path = '/opt/hawkeye/pic/result.csv'
df = pd.read_csv(path,
                 usecols=[
                     'code', 'last_date', 'start price', 'sim_mean', 'sim_diff',
                     'VaR 99%', 'VaR 99% Percent', 'volume_mean',
                     'return_mean', 'return_sigma'
                 ])
df.head()
df['sim_diff'] = round(df['sim_diff'] / df['start price'] * 100, 3)
print(len(df))

print(df['start price'].quantile(0.7))
print(df['sim_diff'].quantile(0.9))

volume_threshold = df['volume_mean'].quantile(0.2)
df = df[(df['volume_mean'] > volume_threshold) & (df['start price'] > 0.15)]
print(len(df))
df.sort_values(by='sim_diff', ascending=False).head(20)

1571
0.88
1.188
617

,code,last_date,start price,sim_mean,sim_diff,VaR 99%,VaR 99% Percent,volume_mean,return_mean,return_sigma
233,AVH,2019-05-16,0.490,0.51,4.270,0.0617,12.5851,8.355594e+06,0.021652,0.075526
1121,NSC,2019-05-17,0.615,0.64,4.088,0.2341,38.0629,5.134245e+04,0.019579,0.208017
44,ANO,2019-05-17,4.700,4.87,3.709,0.4817,10.2487,9.394618e+04,0.018749,0.063133
13,8CO,2019-05-16,0.155,0.16,3.411,0.0196,12.6668,2.427746e+05,0.017100,0.074168
551,E2M,2019-05-10,0.275,0.28,3.340,0.0315,11.4376,1.754284e+05,0.016824,0.068264
172,ATU,2019-05-16,0.350,0.36,3.068,0.0489,13.9729,6.851132e+05,0.016391,0.075468
962,LCK,2019-05-10,0.310,0.32,2.663,0.0691,22.2822,3.090869e+06,0.013705,0.120474
93,AGH,2019-05-17,0.620,0.64,2.624,0.0554,8.9373,4.481264e+05,0.013553,0.051464
1570,ZNO,2019-05-17,0.160,0.16,2.610,0.0395,24.6943,1.657874e+05,0.013208,0.129736
211,ALF,2019-05-17,0.890,0.91,2.575,0.2674,30.0477,1.070458e+05,0.011926,0.162716
1569,Z1P,2019-05-17,3.520,3.61,2.573,0.2472,7.0214,2.213021e+06,0.013231,0.041874
1504,WKT,2019-05-17,0.280,0.29,2.461,0.0252,8.9974,7.143732e+05,0.012751,0.052017
335,BUB,2019-05-17,1.255,1.28,2.321,0.1212,9.6573,5.224863e+06,0.012003,0.054048
11,5GN,2019-05-17,1.220,1.25,2.317,0.0982,8.0491,2.783428e+05,0.011851,0.046108
263,BCC,2019-05-16,0.265,0.27,2.178,0.0382,14.4117,5.029777e+04,0.009918,0.077108
1003,MAU,2019-05-10,0.320,0.33,1.972,0.0373,11.6521,7.286872e+04,0.010294,0.061569
400,CIA,2019-05-17,2.810,2.86,1.955,0.2033,7.2333,2.352005e+05,0.010121,0.040556
545,DUB,2019-05-17,0.890,0.91,1.901,0.0853,9.5836,5.230123e+05,0.009455,0.052323
1099,MGX,2019-05-17,1.255,1.28,1.885,0.0598,4.7649,2.889591e+06,0.009759,0.028963
929,KSS,2019-05-10,0.250,0.25,1.877,0.0228,9.1156,3.582942e+05,0.009581,0.050492

In [73]:
# high mean return 
df.sort_values(by='sim_diff', ascending=False).head(10)

,code,last_date,start price,sim_mean,sim_diff,VaR 99%,VaR 99% Percent,volume_mean,return_mean,return_sigma
233,AVH,2019-05-16,0.490,0.51,4.270,0.0617,12.5851,8.355594e+06,0.021652,0.075526
1121,NSC,2019-05-17,0.615,0.64,4.088,0.2341,38.0629,5.134245e+04,0.019579,0.208017
44,ANO,2019-05-17,4.700,4.87,3.709,0.4817,10.2487,9.394618e+04,0.018749,0.063133
13,8CO,2019-05-16,0.155,0.16,3.411,0.0196,12.6668,2.427746e+05,0.017100,0.074168
551,E2M,2019-05-10,0.275,0.28,3.340,0.0315,11.4376,1.754284e+05,0.016824,0.068264
172,ATU,2019-05-16,0.350,0.36,3.068,0.0489,13.9729,6.851132e+05,0.016391,0.075468
962,LCK,2019-05-10,0.310,0.32,2.663,0.0691,22.2822,3.090869e+06,0.013705,0.120474
93,AGH,2019-05-17,0.620,0.64,2.624,0.0554,8.9373,4.481264e+05,0.013553,0.051464
1570,ZNO,2019-05-17,0.160,0.16,2.610,0.0395,24.6943,1.657874e+05,0.013208,0.129736
211,ALF,2019-05-17,0.890,0.91,2.575,0.2674,30.0477,1.070458e+05,0.011926,0.162716

In [74]:
# high price
df[df['start price']>1].sort_values(by='sim_diff', ascending=False).head(10)

,code,last_date,start price,sim_mean,sim_diff,VaR 99%,VaR 99% Percent,volume_mean,return_mean,return_sigma
44,ANO,2019-05-17,4.700,4.87,3.709,0.4817,10.2487,9.394618e+04,0.018749,0.063133
1569,Z1P,2019-05-17,3.520,3.61,2.573,0.2472,7.0214,2.213021e+06,0.013231,0.041874
335,BUB,2019-05-17,1.255,1.28,2.321,0.1212,9.6573,5.224863e+06,0.012003,0.054048
11,5GN,2019-05-17,1.220,1.25,2.317,0.0982,8.0491,2.783428e+05,0.011851,0.046108
400,CIA,2019-05-17,2.810,2.86,1.955,0.2033,7.2333,2.352005e+05,0.010121,0.040556
1099,MGX,2019-05-17,1.255,1.28,1.885,0.0598,4.7649,2.889591e+06,0.009759,0.028963
1130,NEA,2019-05-17,3.830,3.90,1.845,0.2068,5.3995,2.758876e+06,0.009782,0.032158
479,CRD,2019-05-17,1.725,1.76,1.836,0.1362,7.8970,2.516973e+05,0.009541,0.043361
893,JIN,2019-05-17,17.640,17.96,1.833,0.7882,4.4680,2.944424e+05,0.009616,0.028292
572,EXL,2019-05-17,5.310,5.41,1.793,0.4407,8.3001,3.914424e+05,0.009079,0.045529

In [75]:
# highest price
df[df['sim_diff']>0.8].sort_values(by='start price', ascending=False).head(10)

,code,last_date,start price,sim_mean,sim_diff,VaR 99%,VaR 99% Percent,volume_mean,return_mean,return_sigma
1550,XRO,2019-05-17,61.30,61.90,0.975,2.3930,3.9038,4.080842e+05,0.004924,0.021471
1000,MFG,2019-05-17,44.82,45.45,1.414,1.2863,2.8700,5.603837e+05,0.007133,0.018919
94,ALU,2019-05-17,32.61,32.91,0.918,1.7672,5.4191,4.877692e+05,0.005079,0.027926
427,CUV,2019-05-17,31.46,31.82,1.147,1.9338,6.1467,1.038602e+05,0.006013,0.031563
55,APT,2019-05-17,25.60,26.01,1.599,1.8189,7.1050,2.085872e+06,0.008506,0.038436
130,APX,2019-05-17,25.19,25.60,1.631,1.4067,5.5843,8.024468e+05,0.008101,0.031709
324,BRG,2019-05-17,18.21,18.43,1.184,0.7355,4.0389,2.940396e+05,0.006033,0.023060
893,JIN,2019-05-17,17.64,17.96,1.833,0.7882,4.4680,2.944424e+05,0.009616,0.028292
1515,WEB,2019-05-17,16.80,16.95,0.877,1.2359,7.3568,5.458244e+05,0.004770,0.036727
811,IEL,2019-05-17,16.72,16.91,1.159,0.7831,4.6836,6.902328e+05,0.005996,0.025482

In [76]:
# low risk
var_threshold = df['VaR 99% Percent'].quantile(0.3)
print(var_threshold)
df[df['VaR 99% Percent'] < var_threshold].sort_values(by='sim_diff',
                                                      ascending=False).head(10)

3.8983599999999994

,code,last_date,start price,sim_mean,sim_diff,VaR 99%,VaR 99% Percent,volume_mean,return_mean,return_sigma
176,AD8,2019-05-17,7.11,7.21,1.418,0.2750,3.8684,1.804788e+05,0.007450,0.023410
1000,MFG,2019-05-17,44.82,45.45,1.414,1.2863,2.8700,5.603837e+05,0.007133,0.018919
523,DDR,2019-05-17,5.14,5.21,1.273,0.1544,3.0036,1.273768e+05,0.006611,0.018334
859,IVC,2019-05-17,15.46,15.60,0.876,0.5755,3.7228,4.941825e+05,0.004526,0.020465
1484,VRL,2019-05-17,3.77,3.80,0.823,0.0966,2.5632,2.245945e+05,0.004269,0.015027
1454,A2M,2019-05-16,15.38,15.50,0.791,0.5765,3.7481,2.953829e+06,0.004275,0.020185
618,EHE,2019-05-17,2.97,2.99,0.751,0.1087,3.6583,1.015350e+06,0.003810,0.019733
1091,MND,2019-05-17,18.97,19.11,0.742,0.5438,2.8666,3.380912e+05,0.003934,0.015736
197,ASB,2019-05-17,2.74,2.76,0.740,0.0931,3.3962,9.360224e+05,0.003894,0.018269
1314,SSM,2019-05-17,2.46,2.48,0.731,0.0853,3.4681,1.295535e+06,0.003756,0.018631

In [77]:
# high volume
df.sort_values(by='volume_mean', ascending=False).head(10)

,code,last_date,start price,sim_mean,sim_diff,VaR 99%,VaR 99% Percent,volume_mean,return_mean,return_sigma
1444,TLS,2019-05-16,3.51,3.53,0.431,0.0931,2.6519,2.634859e+07,0.002249,0.013454
672,FMG,2019-05-17,8.95,9.10,1.713,0.3893,4.3499,1.893690e+07,0.008612,0.027161
1355,S32,2019-05-17,3.52,3.53,0.280,0.1070,3.0403,1.817144e+07,0.001425,0.015186
769,HSO,2019-05-17,2.45,2.46,0.378,0.0456,1.8624,1.284986e+07,0.001942,0.009660
1081,MGR,2019-05-17,2.95,2.97,0.541,0.0593,2.0110,1.271401e+07,0.002683,0.011212
1480,VCX,2019-05-17,2.58,2.58,-0.048,0.0665,2.5771,1.225923e+07,-0.000244,0.011103
97,AWC,2019-05-17,2.39,2.40,0.360,0.0879,3.6763,1.186764e+07,0.001834,0.017616
106,AMP,2019-05-17,2.20,2.20,-0.101,0.1107,5.0319,1.176785e+07,-0.000381,0.022085
1293,SCG,2019-05-17,3.84,3.84,-0.029,0.0989,2.5743,1.164832e+07,-0.000170,0.011574
1160,NEC,2019-05-17,1.88,1.89,0.622,0.0875,4.6541,9.392770e+06,0.003329,0.023546

In [13]:
# plt.figure(figsize=(16,8))
df['volume_mean'].quantile(0.2)

2628142.383838384

In [81]:
# 2019-05-17 recommendations
selection = [
    'AVH',  # high return & high risk
    'ANO',  # high return & high risk
    'AGH',  # high return & meduim risk
    'Z1P',  # medium price & risk
    'MFG',  # high price & low risk
    'AD8',  # low risk
    'FMG',  # high volume & low risk
]
df[df['code'].isin(selection)].sort_values(by='sim_diff', ascending=False).head(10)

,code,last_date,start price,sim_mean,sim_diff,VaR 99%,VaR 99% Percent,volume_mean,return_mean,return_sigma
233,AVH,2019-05-16,0.49,0.51,4.270,0.0617,12.5851,8.355594e+06,0.021652,0.075526
44,ANO,2019-05-17,4.70,4.87,3.709,0.4817,10.2487,9.394618e+04,0.018749,0.063133
93,AGH,2019-05-17,0.62,0.64,2.624,0.0554,8.9373,4.481264e+05,0.013553,0.051464
1569,Z1P,2019-05-17,3.52,3.61,2.573,0.2472,7.0214,2.213021e+06,0.013231,0.041874
672,FMG,2019-05-17,8.95,9.10,1.713,0.3893,4.3499,1.893690e+07,0.008612,0.027161
176,AD8,2019-05-17,7.11,7.21,1.418,0.2750,3.8684,1.804788e+05,0.007450,0.023410
1000,MFG,2019-05-17,44.82,45.45,1.414,1.2863,2.8700,5.603837e+05,0.007133,0.018919